'use client';

import { AlertCircle, ArrowLeft, Hammer, Loader2, Save } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useId, useRef, useState, useTransition } from 'react';

import { BuildStatusBadge, RuntimeStatusBadge } from '@/components/admin/runtime-badges';
import { Button } from '@/components/ui/button';
import { getBuildAction, queueBuildAction, updateRuntimeAction } from '@/lib/runtime/actions';
import { generateDockerfile } from '@/lib/runtime/dockerfile';
import type { BuildStatus, RuntimeStatus } from '@/lib/runtime/types';
import { cn } from '@/lib/utils';

/** Python versions offered by the micromamba base image (PRD §10.4). */
const PYTHON_VERSIONS = ['3.10', '3.11', '3.12'] as const;

/** A build a runtime status considers "still working" — worth polling. */
const LIVE_BUILD_STATUSES: readonly BuildStatus[] = ['queued', 'running'];
function isLiveBuild(status: BuildStatus): boolean {
  return LIVE_BUILD_STATUSES.includes(status);
}

/** Serializable runtime detail built server-side in app/admin/runtimes/[id]/page.tsx. */
export interface RuntimeDetailData {
  id: string;
  name: string;
  courseTitle: string | null;
  pythonVersion: string;
  condaPackages: string[];
  pipPackages: string[];
  aptPackages: string[];
  baseImage: string;
  memoryLimit: string;
  timeoutSeconds: number;
  status: RuntimeStatus;
  imageTag: string | null;
}

export interface BuildHistoryRow {
  id: string;
  status: BuildStatus;
  log: string;
  imageTag: string | null;
  createdAt: string;
  finishedAt: string | null;
}

export interface RuntimeDetailProps {
  runtime: RuntimeDetailData;
  builds: BuildHistoryRow[];
}

/** Split a textarea (one token per line, commas tolerated) into a clean list. */
function linesToList(text: string): string[] {
  return text
    .split(/[\n,]/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function listToText(list: string[]): string {
  return list.join('\n');
}

/**
 * Admin Runtime Studio — detail/edit surface (client).
 *
 * Edits the container recipe (python version + conda/pip/apt packages + memory
 * / timeout caps), shows a LIVE, read-only Dockerfile preview generated by the
 * exact same pure `generateDockerfile` the server writes to the build context
 * (byte-identical for a given recipe), and drives a build: "빌드 실행" persists
 * the recipe then queues a build, after which the log viewer polls
 * getBuildAction every ~2s until the build reaches a terminal state. All
 * mutations are app_admin-gated server-side in lib/runtime.
 */
export function RuntimeDetail({ runtime, builds }: RuntimeDetailProps) {
  const router = useRouter();

  const [name, setName] = useState(runtime.name);
  const [pythonVersion, setPythonVersion] = useState(runtime.pythonVersion);
  const [condaText, setCondaText] = useState(listToText(runtime.condaPackages));
  const [pipText, setPipText] = useState(listToText(runtime.pipPackages));
  const [aptText, setAptText] = useState(listToText(runtime.aptPackages));
  const [memoryLimit, setMemoryLimit] = useState(runtime.memoryLimit);
  const [timeoutSeconds, setTimeoutSeconds] = useState(String(runtime.timeoutSeconds));

  const [formError, setFormError] = useState<string | null>(null);
  const [isSaving, startSave] = useTransition();

  // Live build being polled. Seeded from the newest build if it's still working.
  const newest = builds[0];
  const [activeBuild, setActiveBuild] = useState<BuildHistoryRow | null>(
    newest && isLiveBuild(newest.status) ? newest : null,
  );
  const [buildError, setBuildError] = useState<string | null>(null);
  const [isQueuing, startQueue] = useTransition();

  const nameId = useId();
  const pyId = useId();
  const condaId = useId();
  const pipId = useId();
  const aptId = useId();
  const memId = useId();
  const timeoutId = useId();

  // --- Live Dockerfile preview (pure, deterministic, same fn as the worker) ---
  const dockerfile = generateDockerfile({
    base_image: runtime.baseImage,
    python_version: pythonVersion,
    conda_packages: linesToList(condaText),
    pip_packages: linesToList(pipText),
    apt_packages: linesToList(aptText),
  });

  /** Validate + assemble the recipe config from the form. Returns null on error. */
  const buildConfig = useCallback(() => {
    const trimmedName = name.trim();
    if (!trimmedName) {
      setFormError('런타임 이름을 입력하세요.');
      return null;
    }
    if (!/^\d+(m|g)$/i.test(memoryLimit.trim())) {
      setFormError('메모리 한도 형식이 올바르지 않습니다. 예: 512m, 1g');
      return null;
    }
    const timeout = Number(timeoutSeconds);
    if (!Number.isInteger(timeout) || timeout < 1 || timeout > 600) {
      setFormError('타임아웃은 1~600초 사이의 정수여야 합니다.');
      return null;
    }
    setFormError(null);
    return {
      name: trimmedName,
      python_version: pythonVersion,
      conda_packages: linesToList(condaText),
      pip_packages: linesToList(pipText),
      apt_packages: linesToList(aptText),
      memory_limit: memoryLimit.trim(),
      timeout_seconds: timeout,
    };
  }, [name, memoryLimit, timeoutSeconds, pythonVersion, condaText, pipText, aptText]);

  const handleSave = useCallback(() => {
    const config = buildConfig();
    if (!config) return;
    startSave(async () => {
      const result = await updateRuntimeAction(runtime.id, config);
      if (!result.ok) {
        setFormError(result.error);
        return;
      }
      router.refresh();
    });
  }, [buildConfig, runtime.id, router]);

  const handleBuild = useCallback(() => {
    const config = buildConfig();
    if (!config) return;
    setBuildError(null);
    startQueue(async () => {
      // Persist the current recipe first so the image matches exactly what the
      // preview shows, then queue the build against it.
      const saved = await updateRuntimeAction(runtime.id, config);
      if (!saved.ok) {
        setBuildError(saved.error);
        return;
      }
      const queued = await queueBuildAction(runtime.id);
      if (!queued.ok) {
        setBuildError(queued.error);
        return;
      }
      setActiveBuild({
        id: queued.data,
        status: 'queued',
        log: '',
        imageTag: null,
        createdAt: new Date().toISOString(),
        finishedAt: null,
      });
      router.refresh();
    });
  }, [buildConfig, runtime.id, router]);

  // --- Poll the active build every ~2s until it reaches a terminal state. ---
  const routerRef = useRef(router);
  routerRef.current = router;
  const activeBuildId = activeBuild && isLiveBuild(activeBuild.status) ? activeBuild.id : null;

  useEffect(() => {
    if (!activeBuildId) return;
    let cancelled = false;
    const timer = setInterval(async () => {
      const result = await getBuildAction(activeBuildId);
      if (cancelled) return;
      if (!result.ok) {
        setBuildError(result.error);
        return;
      }
      const build = result.data;
      if (!build) return;
      setActiveBuild({
        id: build.id,
        status: build.status,
        log: build.log,
        imageTag: build.image_tag,
        createdAt: build.created_at,
        finishedAt: build.finished_at,
      });
      if (!isLiveBuild(build.status)) {
        // Terminal — refresh the RSC so runtime status + build history update.
        routerRef.current.refresh();
      }
    }, 2000);
    return () => {
      cancelled = true;
      clearInterval(timer);
    };
  }, [activeBuildId]);

  const isBusy = isSaving || isQueuing;

  return (
    <div className="mx-auto max-w-4xl px-6 py-10 sm:px-10">
      <Link
        href="/admin/runtimes"
        className="mb-6 inline-flex items-center gap-1.5 text-sm text-muted hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
      >
        <ArrowLeft size={14} aria-hidden="true" />
        런타임 목록
      </Link>

      <header className="mb-8 flex items-start justify-between gap-4">
        <div className="min-w-0">
          <p className="font-mono text-xs uppercase tracking-[0.14em] text-muted">Runtime</p>
          <div className="mt-1.5 flex items-center gap-3">
            <h1 className="truncate font-serif text-3xl text-ink">{runtime.name}</h1>
            <RuntimeStatusBadge status={runtime.status} />
          </div>
          <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-0.5 text-xs text-muted">
            {runtime.courseTitle ? <span>{runtime.courseTitle}</span> : null}
            {runtime.imageTag ? (
              <span className="font-mono text-ink">이미지: {runtime.imageTag}</span>
            ) : (
              <span>빌드된 이미지 없음</span>
            )}
          </div>
        </div>
      </header>

      {/* --- Recipe editor --- */}
      <section className="rounded-2xl border border-border bg-paper p-5">
        <h2 className="mb-4 font-serif text-lg text-ink">런타임 구성</h2>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-1.5">
            <label htmlFor={nameId} className="text-xs font-medium text-ink">
              이름
            </label>
            <input
              id={nameId}
              value={name}
              onChange={(e) => setName(e.target.value)}
              autoComplete="off"
              className="h-9 rounded-lg border border-border bg-white px-2.5 text-sm text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <label htmlFor={pyId} className="text-xs font-medium text-ink">
              Python 버전
            </label>
            <select
              id={pyId}
              value={pythonVersion}
              onChange={(e) => setPythonVersion(e.target.value)}
              className="h-9 rounded-lg border border-border bg-white px-2.5 text-sm text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            >
              {PYTHON_VERSIONS.map((v) => (
                <option key={v} value={v}>
                  {v}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="mt-4 grid gap-4 sm:grid-cols-3">
          <PackageField
            id={condaId}
            label="conda 패키지"
            hint="conda-forge · 한 줄에 하나"
            value={condaText}
            onChange={setCondaText}
            placeholder={'numpy\npandas'}
          />
          <PackageField
            id={pipId}
            label="pip 패키지"
            hint="PyPI · 한 줄에 하나"
            value={pipText}
            onChange={setPipText}
            placeholder={'requests\nrich'}
          />
          <PackageField
            id={aptId}
            label="apt 패키지"
            hint="시스템 · 한 줄에 하나"
            value={aptText}
            onChange={setAptText}
            placeholder={'graphviz'}
          />
        </div>

        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-1.5">
            <label htmlFor={memId} className="text-xs font-medium text-ink">
              메모리 한도
            </label>
            <input
              id={memId}
              value={memoryLimit}
              onChange={(e) => setMemoryLimit(e.target.value)}
              placeholder="512m"
              autoComplete="off"
              className="h-9 rounded-lg border border-border bg-white px-2.5 font-mono text-sm text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            />
            <span className="text-[11px] text-muted">예: 512m, 1g</span>
          </div>
          <div className="flex flex-col gap-1.5">
            <label htmlFor={timeoutId} className="text-xs font-medium text-ink">
              타임아웃 (초)
            </label>
            <input
              id={timeoutId}
              type="number"
              min={1}
              max={600}
              value={timeoutSeconds}
              onChange={(e) => setTimeoutSeconds(e.target.value)}
              className="h-9 rounded-lg border border-border bg-white px-2.5 font-mono text-sm text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            />
            <span className="text-[11px] text-muted">1~600초</span>
          </div>
        </div>

        {formError ? (
          <p role="alert" className="mt-3 flex items-center gap-1.5 text-sm text-red-600">
            <AlertCircle size={14} aria-hidden="true" />
            {formError}
          </p>
        ) : null}

        <div className="mt-5 flex flex-wrap items-center gap-2">
          <Button type="button" variant="outline" onClick={handleSave} disabled={isBusy}>
            {isSaving ? (
              <Loader2 size={16} className="animate-spin" aria-hidden="true" />
            ) : (
              <Save size={16} aria-hidden="true" />
            )}
            저장
          </Button>
          <Button type="button" variant="accent" onClick={handleBuild} disabled={isBusy}>
            {isQueuing ? (
              <Loader2 size={16} className="animate-spin" aria-hidden="true" />
            ) : (
              <Hammer size={16} aria-hidden="true" />
            )}
            빌드 실행
          </Button>
          <span className="text-xs text-muted">
            저장·빌드 시 런타임은 초안으로 되돌아가며 다시 빌드됩니다.
          </span>
        </div>
        {buildError ? (
          <p role="alert" className="mt-2 flex items-center gap-1.5 text-sm text-red-600">
            <AlertCircle size={14} aria-hidden="true" />
            {buildError}
          </p>
        ) : null}
      </section>

      {/* --- Dockerfile preview (live, read-only) --- */}
      <section className="mt-6 rounded-2xl border border-border bg-paper p-5">
        <h2 className="mb-3 font-serif text-lg text-ink">Dockerfile 미리보기</h2>
        <p className="mb-3 text-xs text-muted">
          서버가 생성하는 Dockerfile입니다. 편집 내용이 실시간으로 반영되며 직접 수정할 수
          없습니다.
        </p>
        <pre
          className="max-h-96 overflow-auto rounded-lg border border-border bg-rail px-4 py-3 font-mono text-xs leading-relaxed text-canvas"
          aria-label="생성된 Dockerfile"
        >
          {dockerfile}
        </pre>
      </section>

      {/* --- Active build status + log viewer --- */}
      {activeBuild ? (
        <section className="mt-6 rounded-2xl border border-border bg-paper p-5">
          <div
            className="mb-3 flex items-center gap-2"
            role="status"
            aria-live="polite"
            aria-atomic="true"
          >
            <h2 className="font-serif text-lg text-ink">빌드 로그</h2>
            <BuildStatusBadge status={activeBuild.status} />
            {isLiveBuild(activeBuild.status) ? (
              <span className="flex items-center gap-1 text-xs text-muted">
                <Loader2 size={12} className="animate-spin" aria-hidden="true" />
                진행 중…
              </span>
            ) : null}
            {activeBuild.status === 'succeeded' && activeBuild.imageTag ? (
              <span className="font-mono text-xs text-ink">{activeBuild.imageTag}</span>
            ) : null}
          </div>
          <pre
            className="max-h-80 overflow-auto rounded-lg border border-border bg-rail px-4 py-3 font-mono text-xs leading-relaxed text-canvas"
            aria-label="빌드 로그 출력"
          >
            {activeBuild.log || '로그를 기다리는 중…'}
          </pre>
        </section>
      ) : null}

      {/* --- Build history --- */}
      <section className="mt-6 rounded-2xl border border-border bg-paper p-5">
        <h2 className="mb-3 font-serif text-lg text-ink">빌드 히스토리</h2>
        {builds.length === 0 ? (
          <p className="text-sm text-muted">아직 빌드 기록이 없습니다.</p>
        ) : (
          <ul className="flex flex-col divide-y divide-border">
            {builds.map((b) => (
              <li key={b.id} className="flex items-center justify-between gap-4 py-2.5">
                <div className="flex items-center gap-3">
                  <BuildStatusBadge status={b.status} />
                  <span className="font-mono text-xs text-muted">
                    {new Date(b.createdAt).toLocaleString('ko-KR')}
                  </span>
                </div>
                {b.imageTag ? (
                  <span className="truncate font-mono text-xs text-ink">{b.imageTag}</span>
                ) : null}
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}

interface PackageFieldProps {
  id: string;
  label: string;
  hint: string;
  value: string;
  onChange: (value: string) => void;
  placeholder: string;
}

function PackageField({ id, label, hint, value, onChange, placeholder }: PackageFieldProps) {
  return (
    <div className={cn('flex flex-col gap-1.5')}>
      <label htmlFor={id} className="text-xs font-medium text-ink">
        {label}
      </label>
      <textarea
        id={id}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        rows={4}
        spellCheck={false}
        className="resize-y rounded-lg border border-border bg-white px-2.5 py-2 font-mono text-xs text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
      />
      <span className="text-[11px] text-muted">{hint}</span>
    </div>
  );
}
